name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Discord Bot Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Node.js if not installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_23.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install pnpm if not installed
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm@9.4.0
            fi

            # Create and navigate to app directory if it doesn't exist
            if [ ! -d "~/discord-bot" ]; then
              git clone https://github.com/the-muel-git/eliza.git ~/discord-bot
            fi

            cd ~/discord-bot

            # Reset any local changes and pull latest
            git fetch origin
            git reset --hard origin/main

            # Copy environment file if it doesn't exist
            if [ ! -f ".env" ]; then
              cp .env.example .env
            fi

            # Run the deployment script
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh